# Generated by Django 6.0.1 on 2026-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='project',
            name='collaborator_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of auth.User.id integers'),
        ),
    ]
