# Generated by Django 6.0.1 on 2026-04-16 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Users invited to work on this project', related_name='shared_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(help_text='References auth.User.id in the auth database')),
                ('from_stage', models.CharField(choices=[('BACKLOG', 'Product Backlog'), ('SPRINT', 'Sprint Backlog'), ('TEST', 'Ready for Test'), ('DONE', 'Complete')], max_length=10)),
                ('to_stage', models.CharField(choices=[('BACKLOG', 'Product Backlog'), ('SPRINT', 'Sprint Backlog'), ('TEST', 'Ready for Test'), ('DONE', 'Complete')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_comments', to='sprints.backlogitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
