# Generated by Django 6.0.1 on 2026-04-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_add_unique_name_and_item_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlogitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AddConstraint(
            model_name='backlogitem',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_task_title_per_project'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_sprint_name_per_project'),
        ),
    ]
